language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
branches:
  only:
    - master
sudo: false
script: "npm test"
addons:
  code_climate:
    repo_token: 2ad089728fbd537ae0edeedc46730921fe0cf991e930288085254b181236c301
